
POST http://localhost:8001/account/confirm-reset-password
Accept: application/json
Content-Type: application/json

{
    "email": "errietta261@errietta.me",
    "token": "reset-token",
    "password": "new-pass"
}
